### ISSUE TITLE
Seems to not play well with Dadbod UI

### ISSUE THREAD

**Issue by johnnadratowski** [pbogut/vim-dadbod-ssh#3]
After your response on #2 I decided to give NeoVim a try.  I was able to load the plugin, but now I'm getting another error when using [Dadbod UI](https://github.com/kristijanhusak/vim-dadbod-ui).  It seems that these plugins don't play well together.   This is the error I get when trying to open the Dadbod UI.

```
Error detected while processing function db_ui#open[1]..<SNR>134_init[2]..15[25]..17[2]..20[17]..25[5]..db#resolve[1]..<SNR>135_canonicalize[10]..db#a
dapter#call[5]..db#adapter#ssh#canonicalize:
line    2:
E117: Unknown function: db#adapter#0#canonicalize
```

I was able to successfully query using the `:DB` command however.

**Comment by pbogut** [comment]
This is the same as #1.

I don't use UI plugin but I had a look at it and it looks like it don't like waiting for tunel creation. By default I wait till tunnel is created on first `DB` call, so it can be used right away, otherwise first `DB` call throws errors.

With DBUI it calls `canonicalize` on each connection and then shows the list. I've added option to create tunnels in background by default. That makes them load nice, but not sure what will happen if tunnel is not created yet and you try to use it (didn't happen to me in my short testing, but my feeling is it may be an issue).

To enable this update the plugin and add `let g:db_ssh_default_async = 1` somewhere in your init.
It should make DBUI work correctly. Be aware that if you do something like: `DB ..query..  ssh://.....` before `DBUI` you will get error on first run (rest should work fine).

Please let me know how it goes.

Edit:
After looking again at #1 it looks like `g:db_ssh_default_async` is not needed (although still could be helpful). Without this option set to `1` it will take longer to display UI as it will create all tunnels first, then show UI. With async on it will create tunnels in background so UI can be displayed right away.

**Comment by johnnadratowski** [comment]
@pbogut - I made the requisitie updates and it seems to be working well. I actually tried with `let g:db_ssh_default_async = 1` first, but it timed out after bringing up the `:DBUI` and navigating to the DB, so I restarted it without that configuratio and it worked!

Thanks so much for your help.
